### PR TITLE
Deprecate configurable.environment

### PR DESCRIPTION
**Pull request by domuserk**

### CODE REVIEW

**Review by vitorgamer58 — APPROVED** [review]
Parece bom!

**Comment by vitorgamer58** [comment]
```
PS D:\Documentos\Programação\Nullstack\domuserk\tests> npm test

> test@0.0.1 test D:\Documentos\Programação\Nullstack\domuserk\tests
> jest --testTimeout=20000

 PASS  src/ContextPage.test.js (6.622 s)
 PASS  src/ContextProject.test.js (7.701 s)
 PASS  src/RenderableComponent.test.js (8.278 s)
 PASS  src/TwoWayBindings.test.js
 PASS  src/NestedProxy.test.js
 PASS  src/PureComponents.test.js
 PASS  src/ContextWorker.test.js (13.026 s)
 PASS  src/ServerRequestandResponse.test.js
 PASS  src/StatefulComponent.test.js
 PASS  src/InstanceSelf.test.js
 PASS  src/ContextSettings.test.js
 PASS  src/RoutesAndParams.test.js (18.472 s)
 PASS  src/ErrorPage.test.js (7.079 s)
 PASS  src/ServerFunctions.test.js (6.493 s)
 PASS  src/ContextSecrets.test.js
 PASS  src/PluginAttributes.test.js
 PASS  src/ContextEnvironment.test.js
 PASS  src/ChildComponent.test.js
 PASS  src/FalsyNodes.test.js
 PASS  src/FullStackLifecycle.test.js (5.688 s)
 PASS  src/ParentComponent.test.js
 PASS  src/Instanceable.test.js (5.58 s)
 PASS  src/Context.test.js (5.016 s)
 PASS  src/DateParser.test.js
 PASS  src/InstanceKey.test.js
 PASS  src/ContextData.test.js
 PASS  src/RemoveStart.test.js
 PASS  src/StaticThis.test.js (5.695 s)
 PASS  src/Vunerability.test.js
 PASS  src/Application.test.js
 PASS  src/ErrorOnChildNode.test.js
 PASS  src/Element.test.js
 PASS  src/ScriptRun.test.js

Test Suites: 33 passed, 33 total
Tests:       250 passed, 250 total
Snapshots:   0 total
Time:        44.123 s
Ran all test suites.
```

**Comment by domuserk** [comment]
Ainda 

> Parece bom!
Ainda irei retirar o Proxy

**Comment by Mortaro** [comment]
Vou aguardar remover o proxy para dar merge, mas ja ta melhor! obrigado galera <3

**Comment by Mortaro** [comment]
closing due to inactivity, feel free to reopen if you wanna retry. Thanks!

**Pull request closed without merging**
